name: windows_taskbar
description: Flutter plugin serving utilities related to Windows taskbar.
version: 1.1.2
homepage: https://github.com/alexmercerind/windows_taskbar
repository: https://github.com/alexmercerind/windows_taskbar

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      windows:
        pluginClass: WindowsTaskbarPlugin
